language: java

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

before_install:
  - set JAVA_OPTS=-XX:MaxPermSize=1024m -Xmx1512m -Dfile.encoding=UTF-8
  - set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8

script:
  - curl -i -u firm1:1855d86e2e0e8301b95c0a09973f31e98d560b5f https://api.github.com/repos/steeve/france.code-civil
  - ./gradlew check --info
