language: java

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7
    - os: osx
      osx_image: xcode6

before_install:
  - set JAVA_OPTS=-XX:MaxPermSize=1024m -Xmx1512m -Dfile.encoding=UTF-8
  - set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8

script:
  - ./gradlew check --info